#!/bin/bash

# Colors ANSI codes
NC="\033[0m"
YELLOW="\x1b[33m"
RED="\x1b[31m"
GREEN="\033[32m"

#Dangerous Capabilities list
DANGEROUS_CAPS="cap_sys_admin|cap_sys_ptrace|cap_sys_module|cap_dac_override|cap_chown|cap_fowner"

# Loading Animation
spiner() {
  local pid=$1
  local spin='-\|/'
  local i=0

  while kill -0 "$pid" 2>/dev/null; do
    i=$(( (i+1) % 4 ))
    printf "\r[%c] Scanning system, please wait..." "${spin:$i:1}"
    sleep 0.1
  done

  printf "                      \n"
}

# help message
show_help() {
    echo "Usage: vulners [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  -h, --help    Show this help message and exit"
    echo "  -l, --log     Run audit and save output to a log file"
    echo ""
}

# Search SUID files
search_suid() {
  echo ""
  echo -e "${YELLOW} [*] Scanning for dangerous SUID binaries...${NC}"
  echo "--------------------------------------------------"


  local suid_var
  suid_var=$(find / -type f -perm -4000 2> /dev/null | grep -v "/proc") &

  spiner $!

  if [ -z "$suid_var" ]; then
    echo -e "${GREEN} [OK] No vulnerabilities found. ${NC}"
  else
    echo -e "${RED} [CRITICAL] Vulnerable files with SUID found. ${NC}"
    echo "$suid_var"
  fi

  echo "--------------------------------------------------"

}

# World-writable_files
world_writable() {
  echo ""
  echo -e "${YELLOW} [*] Scanning for world-writable files...${NC}"
  echo "--------------------------------------------------"

  tmpfile=$(mktemp)
  find / -type f -perm -o+w 2>/dev/null | grep -v "/proc" | grep -v /sys > "$tmpfile" &
  spiner $!
  suid_var=$(cat "$tmpfile")
  rm -f "$tmpfile"
  
  if [ -z "$suid_var" ]; then
    echo -e "${GREEN} [OK] No vulnerabilities found. ${NC}"
  else
    echo -e "${RED} [CRITICAL] World-writable files found. ${NC}"
    echo "$suid_var"
  fi

  echo "--------------------------------------------------"

}

#check sticky /tmp
echo_sticky_tmp() {
  echo ""
  echo -e "${YELLOW} [*] Checking sticky bit in /tmp...${NC}"
  echo "--------------------------------------------------"
  sticky_info=$(ls -ld /tmp | awk '{print substr($1,length($1)-1,1)}')
  if [[ "$sticky_info" == "t" || "$sticky_info" == "T" ]]; then
    echo -e "${GREEN} [OK] No vulnerabilities found.  ${NC}" 
  else
    echo -e "${RED}sticky bit is missing on /tmp${NC}" 
  fi
}

#check Dangerous Capabilities
check_capabilities() {
  echo ""
  echo -e "${YELLOW} [*] Checking Dangerous Capabilities...${NC}"
  echo "--------------------------------------------------"

  tmpfile=$(mktemp)
  getcap -r / 2>/dev/null > "$tmpfile" &
  spiner $!
  all_cap=$(cat "$tmpfile")
  rm -f "$tmpfile"
  cap_res=$(echo "$all_cap" | grep -E "$DANGEROUS_CAPS")
  if [ -z "$cap_res" ]; then
    echo -e "${GREEN}[OK] No vulnerabilities found. ${NC}"
  else
    echo -e "${RED}[CRITICAL] Dangerous capabilities found. ${NC} "
    echo "$cap_res"  
  fi
  echo ""
}

# Check for empty password
empty_password() {
  echo ""
  echo -e "${YELLOW} [*] Checking /etc/shadow for empty password...${NC}"
  echo "--------------------------------------------------"

  local empass_var
  empass_var=$(awk -F: '$2 == "" { print $1 }' /etc/shadow)
  
  if [ -z "$empass_var" ]; then
    echo -e "${GREEN} [OK] No vulnerabilities found. ${NC}"
  else
    echo -e "${RED} [CRITICAL] Empty passwords found. ${NC}"
    echo "$empass_var"
  fi

  echo "--------------------------------------------------"
}





# Sudoers configuration
sudoers() {
    echo ""
    echo -e "${YELLOW}[*] Analyzing sudoers misconfigurations...${NC}"
    echo "------------------------------------------------"
    
    local sudo_errors
    sudo_errors=$(sudo grep -r "NOPASSWD" /etc/sudoers /etc/sudoers.d/ 2>/dev/null | grep -v ":#")
    
    if [ -z "$sudo_errors" ]; then
        echo -e "${GREEN}[OK] No active NOPASSWD rules found. System is safe.${NC}"
    else
        echo -e "${RED}[CRITICAL] Dangerous NOPASSWD rules detected!${NC}"
        echo "$sudo_errors"
    fi
    
    echo "------------------------------------------------"
    echo ""
}

# Check root
check_root() {
    if [ "$EUID" -ne 0 ]; then
        echo -e "${RED}[-] Error: This script must be run as root!${NC}"
        exit 1
    fi
}

# run func
run_audit() {
  clear          
  check_root
  search_suid    
  world_writable 
  empty_password
  echo_sticky_tmp
  sudoers
  check_capabilities
}

main() {
  case "$1" in
    -h|--help)
      show_help
      exit 0
      ;;
    -l|--log)
      LOG_FILE="/var/log/vulners.log"
      echo -e "${YELLOW}[*] Starting security audit...${NC}"
      echo -e "${YELLOW}[*] All details will be saved to: $LOG_FILE${NC}"
      echo "------------------------------------------------"
      
      run_audit > "$LOG_FILE" 2>&1



      echo -e "${GREEN}[+] Audit successfully finished!${NC}"
      echo -e "${GREEN}[+] To view the results, run:${NC} cat $LOG_FILE"
      echo "------------------------------------------------"
      ;;
    "")
      run_audit
      ;;
    *)
      echo -e "${RED} Error: Unknown argument: '$1'${NC}"
      show_help
      exit 0
      ;;
  esac
}


main "$1"
