#!/bin/bash

# Colors ANSI codes
NC="\033[0m"
YELLOW="\x1b[33m"
RED="\x1b[31m"
GREEN="\033[32m"


# help message
show_help() {
    echo "Usage: vulners [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  -h, --help    Show this help message and exit"
    echo "  -l, --log     Run audit and save output to a log file"
    echo ""
}

# Search SUID files
search_suid() {
  echo -e "${YELLOW} [*] Scanning for dangerous SUID binaries...${NC}"
  echo "--------------------------------------------------"
  local suid_var
  suid_var=$(find / -type f -perm -4000 2> /dev/null | grep -v "/proc")

  if [ -z "$suid_var" ]; then
    echo -e "${GREEN} [OK] No vulnerabilities found. ${NC}"
  else
    echo -e "${RED} [CRITICAL] Vulnerable files with SUID found. ${NC}"
    echo "$suid_var"
  fi

  echo "--------------------------------------------------"

}

# World-writable_files
world_writable() {
  echo -e "${YELLOW} [*] Scanning for world-writable files...${NC}"
  echo "--------------------------------------------------"

  local ww_var
  ww_var=$(find / -type f -perm -0002 2> /dev/null | grep -v "/proc")
  
  if [ -z "$ww_var" ]; then
    echo -e "${GREEN} [OK] No vulnerabilities found. ${NC}"
  else
    echo -e "${RED} [CRITICAL] World-writable files found. ${NC}"
    echo "$ww_var"
  fi

  echo "--------------------------------------------------"

}

# Check for empty password
empty_password() {
  echo -e "${YELLOW} [*] Checing /etc/shadow for empty password...${NC}"
  echo "--------------------------------------------------"

  local empass_var
  empass_var=$(awk -F: '$2 == "" { print $1 }' /etc/shadow)
  
  if [ -z "$empass_var" ]; then
    echo -e "${GREEN} [OK] No vulnerabilities found. ${NC}"
  else
    echo -e "${RED} [CRITICAL] Empty passwords found. ${NC}"
    echo "$empass_var"
  fi

  echo "--------------------------------------------------"
}

# Sudoers configuration
sudoers() {
    echo -e "${YELLOW}[*] Analyzing sudoers misconfigurations...${NC}"
    echo "------------------------------------------------"
    
    # 1. Сохраняем вывод команды в ЛОКАЛЬНУЮ переменную
    local sudo_errors
    sudo_errors=$(sudo grep -r "NOPASSWD" /etc/sudoers /etc/sudoers.d/ 2>/dev/null | grep -v ":#")
    
    # 2. Проверяем: если переменная ПУСТАЯ (-z)
    if [ -z "$sudo_errors" ]; then
        echo -e "${GREEN}[OK] No active NOPASSWD rules found. System is safe.${NC}"
    else
        # 3. Если НЕ пустая — включаем тревогу и выводим то, что нашли
        echo -e "${RED}[CRITICAL] Dangerous NOPASSWD rules detected!${NC}"
        echo "$sudo_errors"
    fi
    
    echo "------------------------------------------------"
    echo ""
}

# Check root
check_root() {
    if [ "$EUID" -ne 0 ]; then
        echo -e "${RED}[-] Error: This script must be run as root!${NC}"
        exit 1
    fi
}
check_root_res=$(check_root)

# run func
run_audit() {
  clear          
  check_root     
  search_suid    
  world_writable 
  empty_password 
  sudoers        
}

main() {
  case "$1" in
    -h|--help)
      show_help
      exit 0
      ;;
    -l|--log)
      echo "logging"
      :
      ;;
    "")
      run_audit
      ;;
    *)
      echo -e "${RED} Error: Unknown argument: '$1'${NC}"
      show_help
      exit 0
      ;;
  esac
}

main $1
