#!/bin/bash

# VulnerS security weights

declare -A WEIGHT

WEIGHT["acl"]=2
WEIGHT["cap"]=6
WEIGHT["empty"]=10
WEIGHT["exec"]=10
WEIGHT["sgid"]=5
WEIGHT["sticky"]=4
WEIGHT["sudoers"]=10
WEIGHT["suid"]=10
WEIGHT["ww"]=5
WEIGHT["wu"]=10
WEIGHT["www"]=4
